import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {motion,AnimatePresence} from "framer-motion";
import {Activity,AlertTriangle,BarChart3,Camera,Car,ChevronLeft,ChevronRight,CircleGauge,Database,Eye,LayoutDashboard,LogOut,MapPinned,Search,Settings,ShieldCheck,Brain,Radio,CheckCircle2} from "lucide-react";
import {LineChart,Line,ResponsiveContainer,Tooltip,BarChart,Bar,XAxis,YAxis,CartesianGrid} from "recharts";
import "./index.css";
import "leaflet/dist/leaflet.css";
import {MapContainer,TileLayer,Marker,Popup,Polyline} from "react-leaflet";

const API=(import.meta.env.VITE_API_URL||"").replace(/\/$/,"");
const nav=[["Dashboard",LayoutDashboard],["Vehicle Tracking",Car],["Live Cameras",Camera],["GIS Trajectory",MapPinned],["Traffic Analytics",BarChart3],["Alerts",AlertTriangle],["Vehicle Database",Database],["AI Lab",Brain],["System Logs",Activity],["Settings",Settings]];

function App(){
 const [token,setToken]=useState(localStorage.getItem("trinetra_token")); const [page,setPage]=useState("Dashboard");
 if(!token) return <Login onLogin={t=>{localStorage.setItem("trinetra_token",t);setToken(t)}}/>;
 return <Shell page={page} setPage={setPage} logout={()=>{localStorage.removeItem("trinetra_token");setToken(null)}}/>;
}
function Login({onLogin}:{onLogin:(t:string)=>void}){
 const [email,setEmail]=useState("admin@trinetra.local"),[password,setPassword]=useState("Admin@123"),[err,setErr]=useState("");
 async function go(e:React.FormEvent){e.preventDefault();let r=await fetch(API+"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});let d=await r.json();if(r.ok)onLogin(d.access_token);else setErr(d.detail||"Login failed")}
 return <div className="login"><div className="orb"/><div className="login-grid"/><div className="login-card"><div className="brand">◈ TRINETRA</div><div className="eyebrow">AI TRAFFIC INTELLIGENCE</div><h1>See. Track.<br/><span>Understand.</span></h1><p>Multi-camera vehicle intelligence command center.</p><form onSubmit={go}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary">ENTER COMMAND CENTER</button></form><div className="login-status"><span>●</span> DEMO AI ENGINE ONLINE</div></div></div>
}
function Shell({page,setPage,logout}:{page:string,setPage:(x:string)=>void,logout:()=>void}){
 const [collapsed,setCollapsed]=useState(false);
 return <div className="app"><aside className={collapsed?"side collapsed":"side"}><div className="side-brand">◈ <b>TRINETRA</b></div>{nav.map(([n,I])=><button className={page===n?"nav active":"nav"} onClick={()=>setPage(n)} key={n as string}><I size={18}/>{!collapsed&&<span>{n}</span>}</button>)}<div className="side-bottom">{!collapsed&&<><div className="status">● AI ENGINE <b>ONLINE</b></div><div className="status">● NETWORK <b>CONNECTED</b></div></>}<button className="nav" onClick={logout}><LogOut size={18}/>{!collapsed&&"Sign out"}</button></div><button className="collapse" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronRight/>:<ChevronLeft/>}</button></aside><main className="main"><header><div><div className="crumb">TRINETRA / COMMAND CENTER</div><h2>{page}</h2></div><div className="header-right"><span className="demo-pill">● DEMO MODE</span><span className="admin">ADMIN</span></div></header><AnimatePresence mode="wait"><motion.div key={page} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="content"><Page page={page}/></motion.div></AnimatePresence></main></div>
}
function Page({page}:{page:string}){
 if(page==="Dashboard")return <Dashboard/>;
 if(page==="Vehicle Tracking")return <Tracking/>;
 if(page==="Live Cameras")return <Cameras/>;
 if(page==="GIS Trajectory")return <GIS/>;
 if(page==="Traffic Analytics")return <Analytics/>;
 if(page==="Alerts")return <Alerts/>;
 if(page==="Vehicle Database")return <Tracking/>;
 if(page==="AI Lab")return <AILab/>;
 return <Placeholder title={page}/>;
}
function Dashboard(){const [s,setS]=useState<any>({});const [events,setEvents]=useState<any[]>([]);useEffect(()=>{fetch(API+"/api/dashboard/stats").then(r=>r.json()).then(setS);const w=new WebSocket((API?API.replace(/^http/,"ws"):(location.protocol==="https:"?"wss:":"ws:")+"//"+location.host)+"/ws/live");w.onmessage=e=>setEvents(x=>[JSON.parse(e.data),...x].slice(0,7));return()=>w.close()},[]);return <><div className="hero-row"><div><div className="eyebrow">LIVE OPERATIONS</div><h1>Vehicle Intelligence <span>Command Center</span></h1><p>Unified multi-camera tracking, AI identity resolution and urban traffic analytics.</p></div><button className="primary" onClick={()=>alert("SIH Demo started — live events are now streaming.")}>▶ START SIH DEMO</button></div><div className="metrics">{[["CAMERAS",s.cameras_total,"Network"],["ACTIVE TRACKS",s.active_tracks,"Realtime"],["VEHICLES TODAY",s.vehicles_today?.toLocaleString(),"24h"],["OCR CONFIDENCE",s.ocr_confidence+"%","ANPR"],["TRAFFIC DENSITY",s.traffic_density+"%","Live"],["ALERTS",s.active_alerts,"Open"]].map(([a,b,c])=><div className="metric" key={a as string}><span>{a}</span><strong>{b??"—"}</strong><small>↗ {c}</small></div>)}</div><div className="grid2"><section className="panel map-panel"><div className="panel-head"><h3>LIVE GIS NETWORK</h3><span className="live"><i/> LIVE</span></div><LiveMap events={events}/></section><section className="panel"><div className="panel-head"><h3>REAL-TIME DETECTIONS</h3><span>{events.length} events</span></div><div className="event-list">{events.map((e,i)=><div className="event" key={i}><div className="dot"/><div><b>{e.vehicle_id}</b><p>{e.plate} · {e.camera_id}</p></div><time>{new Date(e.timestamp).toLocaleTimeString()}</time></div>)}</div></section></div></>}
function LiveMap({events=[]}:{events:any[]}){return <MapContainer center={[28.625,77.22]} zoom={13} className="map"><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{events.map((e,i)=><Marker key={i} position={[e.lat,e.lng]}><Popup><b>{e.vehicle_id}</b><br/>{e.plate}<br/>{e.camera_id}</Popup></Marker>)}<Polyline positions={[[28.6139,77.209],[28.62,77.215],[28.6255,77.22],[28.632,77.226],[28.638,77.235]]}/></MapContainer>}
function Tracking(){const [q,setQ]=useState("MP04AB1234"),[v,setV]=useState<any>(null),[m,setM]=useState<any>(null);async function search(){let r=await fetch(API+"/api/tracking/"+q);if(r.ok)setV(await r.json());else setV(null)}async function ai(){let r=await fetch(API+"/api/ai/vehicle-match",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plate:q,color:"White",type:"SUV"})});setM(await r.json())}return <><div className="searchbar"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search plate or vehicle ID"/><button onClick={search}>TRACK</button><button className="ai-btn" onClick={ai}><Brain size={16}/> AI MATCH</button></div>{v&&<div className="profile panel"><div className="vehicle-avatar"><Car size={48}/></div><div><div className="eyebrow">VEHICLE IDENTITY</div><h2>{v.plate}</h2><p>{v.id} · {v.color} · {v.type} · {v.make} {v.model}</p></div><div className="confidence"><small>IDENTITY CONFIDENCE</small><strong>{Math.round(v.confidence*100)}%</strong></div></div>}{v&&<div className="panel"><div className="panel-head"><h3>CHRONOLOGICAL TRAJECTORY</h3><span>{v.total_sightings} sightings</span></div><div className="timeline">{v.observations.map((o:any)=><div className="timeline-item" key={o.id}><div className="tl-dot"/><div><b>{o.camera_id}</b><span>{new Date(o.timestamp).toLocaleTimeString()}</span><p>{o.lat.toFixed(4)}, {o.lng.toFixed(4)} · {o.speed} km/h · {o.direction}</p></div></div>)}</div></div>}{m&&<div className="panel"><div className="panel-head"><h3>AI IDENTITY CANDIDATES</h3><span>Multi-factor matching</span></div><div className="candidates">{m.matches.map((x:any,i:number)=><div className={"candidate "+(i===0?"top":"")} key={x.vehicle.id}><div><b>{x.vehicle.plate}</b><p>{x.vehicle.id} · {x.vehicle.color} {x.vehicle.type}</p></div><div className="score">{Math.round(x.final_score*100)}%<small>{x.confidence}</small></div><div className="evidence">{x.explanation.map((r:string)=><span key={r}>✓ {r}</span>)}</div></div>)}</div></div>}</>}
function Cameras(){const [cs,setCs]=useState<any[]>([]);useEffect(()=>{fetch(API+"/api/cameras").then(r=>r.json()).then(setCs)},[]);return <div className="camera-grid">{cs.map(c=><div className="camera-card panel" key={c.id}><div className="camera-feed"><Radio/><span>DEMO STREAM</span><b>CAM {c.id}</b></div><div className="camera-meta"><div><b>{c.name}</b><p>{c.lat.toFixed(4)}, {c.lng.toFixed(4)}</p></div><span className={c.status==="ONLINE"?"ok":"warn"}>● {c.status}</span></div><div className="mini-stats"><span>FPS <b>{c.fps}</b></span><span>Vehicles/min <b>{120+c.fps}</b></span><span>OCR <b>94%</b></span></div></div>)}</div>}
function GIS(){return <div className="panel full-map"><div className="panel-head"><h3>TRAJECTORY RECONSTRUCTION</h3><span>Vehicle V-00127</span></div><LiveMap events={[]}/></div>}
function Analytics(){const [d,setD]=useState<any>();useEffect(()=>{fetch(API+"/api/analytics").then(r=>r.json()).then(setD)},[]);if(!d)return <div className="loading">Loading analytics…</div>;return <div className="grid2"><div className="panel chart"><div className="panel-head"><h3>VEHICLES / HOUR</h3></div><ResponsiveContainer width="100%" height={300}><LineChart data={d.hourly}><CartesianGrid strokeDasharray="3 3" opacity={.12}/><XAxis dataKey="hour"/><YAxis/><Tooltip/><Line type="monotone" dataKey="vehicles" strokeWidth={3}/></LineChart></ResponsiveContainer></div><div className="panel chart"><div className="panel-head"><h3>CAMERA THROUGHPUT</h3></div><ResponsiveContainer width="100%" height={300}><BarChart data={d.cameras}><XAxis dataKey="camera"/><YAxis/><Tooltip/><Bar dataKey="vehicles"/></BarChart></ResponsiveContainer></div></div>}
function Alerts(){const [a,setA]=useState<any[]>([]);useEffect(()=>{fetch(API+"/api/alerts").then(r=>r.json()).then(setA)},[]);async function resolve(id:string){await fetch(API+"/api/alerts/"+id+"/resolve",{method:"PUT"});setA(await (await fetch(API+"/api/alerts")).json())}return <div className="alert-list">{a.map(x=><div className="panel alert-row" key={x.id}><div className={"sev "+x.severity.toLowerCase()}><AlertTriangle/></div><div><b>{x.type}</b><p>{x.reason}</p><small>{x.camera} · {new Date(x.time).toLocaleString()}</small></div><span className="alert-status">{x.status}</span>{x.status==="OPEN"&&<button onClick={()=>resolve(x.id)}>Resolve</button>}</div>)}</div>}
function AILab(){const [m,setM]=useState<any>();async function run(){let r=await fetch(API+"/api/ai/vehicle-match",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plate:"MP04AB12??",color:"White",type:"SUV"})});setM(await r.json())}return <div className="ai-lab"><div className="ai-flow">{["CAMERA FRAME","VEHICLE DETECTION","PLATE OCR","ATTRIBUTES","RE-ID","MULTI-FACTOR MATCH","GIS TRAJECTORY"].map((x,i)=><motion.div initial={{opacity:0,x:-15}} animate={{opacity:1,x:0}} transition={{delay:i*.08}} className="flow-node" key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}{i<6&&<b>→</b>}</motion.div>)}</div><div className="panel ai-console"><div><div className="eyebrow">EXPLAINABLE AI</div><h2>Vehicle Identity Resolution</h2><p>Test ambiguous plates against historical vehicle identities using configurable multi-factor evidence.</p></div><button className="primary" onClick={run}><Brain size={17}/> RUN AI MATCH</button></div>{m&&<div className="candidates">{m.matches.map((x:any)=><div className="candidate" key={x.vehicle.id}><b>{x.vehicle.plate}</b><div className="score">{Math.round(x.final_score*100)}%<small>{x.confidence}</small></div><div className="evidence">{x.explanation.map((r:string)=><span key={r}>✓ {r}</span>)}</div></div>)}</div>}</div>}
function Placeholder({title}:{title:string}){return <div className="panel empty"><ShieldCheck size={42}/><h2>{title}</h2><p>Module shell is ready for production integration.</p></div>}
createRoot(document.getElementById("root")!).render(<App/>);
